name = "VertexFinder"
uuid = "c0d8f697-7833-4eed-a9bd-1f3da4013f1a"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.1.0"

[compat]
julia = "≥ 1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
